window.dashboardBooted=true;
const state={config:null,me:null,currentView:'overview'};
const commandData=[
['/offer','Send a signing offer to a player.','Manager'],['/canceloffer','Cancel a pending team offer.','Manager'],['/teamoffers','View offers for your team.','Manager'],['/release','Release a player from the roster.','Manager'],['/promote','Promote a player to a coach role.','Manager'],['/demote','Return a coach to player.','Manager'],
['/myoffers','View your pending offers.','Player'],['/teaminfo','View your current team.','Player'],['/teams','List registered teams.','Player'],['/roster','View a team roster.','Player'],['/gametime','Post a scheduled match time.','Allowed role'],
['/addteam','Register a manager and team role.','Admin'],['/removeteam','Remove a team from the bot and website.','Admin'],['/addadmin','Give a member bot-admin access.','Owner'],['/removeadmin','Remove bot-admin access.','Owner'],['/allrosters','View all managers and player rosters.','Admin'],
['/ticketpanel','Post the configured ticket panel.','Admin'],['/rules','Post a rules embed.','Admin'],['/managerlist','Post the manager list.','Admin'],['/totw','Start a private TOTW upload session.','Admin'],['/websiteaccess','Get your secure dashboard link.','Owner']
];
const moduleInfo=[['server','⚙','Server Setup','Logs, channels and core server configuration.'],['teams','♜','Teams & Signings','Manager roles, roster caps and team registration.'],['tickets','🎫','Ticket Builder','Buttons, questions, colours and staff pings.'],['welcome','✦','Welcome & Roles','Welcome embeds and automatic role restoration.'],['gametime','◷','Game Time','Match announcement channel and allowed roles.']];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function notice(message,type='good'){const el=document.getElementById('notice');el.textContent=message;el.className=`notice show ${type}`;setTimeout(()=>el.className='notice',3500)}
async function api(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options,signal:controller.signal});if(!response.ok)throw new Error(await response.text()||'Request failed');return await response.json()}catch(error){if(error.name==='AbortError')throw new Error('The bot dashboard took too long to respond. Refresh the page or check the Railway deployment.');throw error}finally{clearTimeout(timer)}}
function options(items,placeholder='Not configured'){return `<option value="">${placeholder}</option>`+items.map(item=>`<option value="${item.id}">${esc(item.name)}</option>`).join('')}
function fillSelectors(){const c=state.config;document.querySelectorAll('[data-options]').forEach(select=>{const type=select.dataset.options;if(type==='text')select.innerHTML=options(c.channels.filter(x=>x.type==='text'),'Choose a text channel');if(type==='category')select.innerHTML=options(c.channels.filter(x=>x.type==='category'),'Choose a category');if(type==='role'||type==='roles')select.innerHTML=options(c.roles,'Choose roles');if(type==='member')select.innerHTML=options(c.members,'Choose a member')});document.querySelectorAll('[data-setting]').forEach(input=>{const value=c.settings[input.dataset.setting]??'';if(input.type==='checkbox')input.checked=String(value)==='true';else input.value=value});setMulti('excludedRoles',c.excludedRoleIds);setMulti('gametimeRoles',c.gametimeRoleIds)}
function setMulti(id,values){const selected=new Set((values||[]).map(String));document.querySelectorAll(`#${id} option`).forEach(option=>option.selected=selected.has(option.value))}
function getMulti(id){return [...document.getElementById(id).selectedOptions].map(option=>option.value).filter(Boolean)}
function renderOverview(){const c=state.config;document.getElementById('overviewStats').innerHTML=[['Members',c.guild.memberCount],['Configured teams',c.teams.length],['Ticket buttons',c.tickets.length],['Bot modules','7 active']].map(([label,value])=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`).join('');document.getElementById('moduleGrid').innerHTML=moduleInfo.map(([view,icon,title,copy])=>`<article class="module-card" data-open="${view}"><i>${icon}</i><h3>${title}</h3><p>${copy}</p></article>`).join('')}
function renderTeams(){document.getElementById('teamList').innerHTML=state.config.teams.length?state.config.teams.map(team=>`<div class="data-row"><div><b>${esc(team.name)}</b><span>Manager: ${esc(team.managerName)} · ${team.players}/${state.config.settings.roster_cap||22} players</span></div><button class="danger" data-remove-team="${team.roleId}">Remove</button></div>`).join(''):'<div class="data-row"><div><b>No teams configured</b><span>Add the first team using the form above.</span></div></div>'}
function renderTickets(){document.getElementById('ticketList').innerHTML=state.config.tickets.length?state.config.tickets.map((ticket,index)=>`<div class="ticket-row"><i>${esc(ticket.emoji)}</i><div><b>${esc(ticket.label)}</b><small>${ticket.questions.length} questions · ${ticket.pingRoleIds.length} ping roles · ${esc(ticket.style)}</small></div><button class="danger" data-remove-ticket="${index}">Remove</button></div>`).join(''):'<div class="data-row"><div><b>No ticket buttons</b><span>Create your first button above.</span></div></div>'}
function commandCards(list){return list.map(([command,description,access])=>`<article class="command-card"><b>${esc(command)}</b><p>${esc(description)}</p><span>${esc(access)}</span></article>`).join('')}
function renderCommands(){document.getElementById('allCommands').innerHTML=commandCards(commandData)}
function render(){const c=state.config;document.getElementById('guildName').textContent=c.guild.name;document.getElementById('guildMeta').textContent=`${c.guild.memberCount} members · Bot online`;fillSelectors();renderOverview();renderTeams();renderTickets();renderCommands()}
function openView(view){state.currentView=view;document.querySelectorAll('.dash-view').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===view));document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));const active=document.querySelector(`[data-view="${view}"]`);document.getElementById('pageTitle').textContent=active?active.textContent.trim():'Dashboard';document.querySelector('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'auto'})}
async function load(){try{state.me=await api('/api/me');state.config=await api('/api/bot-config');render()}catch(error){notice(error.message||'The dashboard could not load its Discord settings. Refresh once or check Railway.','bad')}}
function gather(){const c=state.config;document.querySelectorAll('[data-setting]').forEach(input=>c.settings[input.dataset.setting]=input.type==='checkbox'?String(input.checked):input.value.trim());c.excludedRoleIds=getMulti('excludedRoles');c.gametimeRoleIds=getMulti('gametimeRoles');return{settings:c.settings,excludedRoleIds:c.excludedRoleIds,gametimeRoleIds:c.gametimeRoleIds,tickets:c.tickets}}
async function save(){const button=document.getElementById('saveButton');button.disabled=true;document.getElementById('saveStatus').textContent='Saving…';try{await api('/api/bot-config',{method:'POST',body:JSON.stringify(gather())});document.getElementById('saveStatus').textContent='All changes saved';notice('Bot configuration saved. Discord will use the new settings immediately.')}catch(error){document.getElementById('saveStatus').textContent='Save failed';notice(error.message,'bad')}finally{button.disabled=false}}
document.addEventListener('click',async event=>{const view=event.target.closest('[data-view]')?.dataset.view||event.target.closest('[data-open]')?.dataset.open;if(view){openView(view);return}const removeTicket=event.target.closest('[data-remove-ticket]');if(removeTicket){state.config.tickets.splice(Number(removeTicket.dataset.removeTicket),1);renderTickets();return}const removeTeam=event.target.closest('[data-remove-team]');if(removeTeam){if(!confirm('Remove this team from the bot?'))return;try{await api('/api/bot-team',{method:'POST',body:JSON.stringify({action:'remove',roleId:removeTeam.dataset.removeTeam})});state.config=await api('/api/bot-config');render();notice('Team removed.')}catch(error){notice(error.message,'bad')}}});
document.getElementById('menuButton').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.getElementById('saveButton').onclick=save;
document.getElementById('websiteContentButton').onclick=()=>{location.href='/?admin=1&v=11'};
document.getElementById('addTeamButton').onclick=async()=>{const roleId=document.getElementById('newTeamRole').value,managerId=document.getElementById('newTeamManager').value;if(!roleId||!managerId)return notice('Choose both a team role and manager.','bad');try{await api('/api/bot-team',{method:'POST',body:JSON.stringify({action:'add',roleId,managerId})});state.config=await api('/api/bot-config');render();notice('Team registered and manager roles assigned.')}catch(error){notice(error.message,'bad')}};
document.getElementById('addTicketButton').onclick=()=>{const label=document.getElementById('ticketName').value.trim();if(!label)return notice('Enter a ticket button name.','bad');state.config.tickets.push({label,emoji:document.getElementById('ticketEmoji').value||'🎫',style:document.getElementById('ticketStyle').value,questions:document.getElementById('ticketQuestions').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,5),pingRoleIds:getMulti('ticketPings')});document.getElementById('ticketName').value='';document.getElementById('ticketQuestions').value='';renderTickets();notice('Ticket button added. Press Save changes to publish the configuration.')};
document.getElementById('commandSearch').oninput=event=>{const query=event.target.value.toLowerCase();document.getElementById('allCommands').innerHTML=commandCards(commandData.filter(item=>item.join(' ').toLowerCase().includes(query)))};
document.getElementById('sendAccessButton').onclick=async()=>{const email=document.getElementById('accessEmail').value.trim();if(!email)return notice('Enter an email address.','bad');try{const result=await api('/api/admin/invite',{method:'POST',body:JSON.stringify({email})});const box=document.getElementById('accessResult');box.className='access-result show';box.innerHTML=`Access created: ${esc(result.inviteUrl)}<br><button class="secondary" id="copyAccess">Copy private link</button>`;document.getElementById('copyAccess').onclick=async()=>{await navigator.clipboard.writeText(result.inviteUrl);notice('Private access link copied.')};const subject=encodeURIComponent('Your APL Bot dashboard access'),body=encodeURIComponent(`You have been invited to manage the APL Discord bot.\n\nOpen this private activation link:\n${result.inviteUrl}\n\nThis activation link expires in 30 minutes.`);location.href=`mailto:${encodeURIComponent(email)}?subject=${subject}&body=${body}`}catch(error){notice(error.message,'bad')}};
document.getElementById('signOut').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};
load();
